apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharedboard-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sharedboard-app
  template:
    metadata:
      labels:
        app: sharedboard-app
    spec:
      containers:
      - image: dockeronetwothree/sharedboard-server:latest
        name: sharedboard-server
        ports:
        - containerPort: 9898
          protocol: TCP
      - image: dockeronetwothree/sharedboard-ui:latest
        name: sharedboard-ui
        ports:
        - containerPort: 8080
          protocol: TCP
